### ISSUE TITLE
Blank page when activating theme on Heroku

### ISSUE THREAD

**Issue by bahoo** [SandersForPresident/WordPress#16]
Per several recommendations, I'm using https://github.com/xyu/heroku-wp as a template for my WordPress on Heroku install. TwentyTen and other default themes work great but the Bernie theme turns up blank.

I've got ACF installed and `gulp build` ran. Let me know if I am missing any other obvious steps.

Haven't had time to dig into it just yet; mostly making a note for myself / anyone else who might be experiencing it. i will close this or submit a PR once I get it nailed down.

**Comment by atticoos** [comment]
Have you seen any traces in the php error logs?

**Comment by bahoo** [comment]
`Catchable fatal error: Object of class stdClass could not be converted to string in /app/public.built/wp-content/themes/Bernie2016/home.php on line 25`

Seems like this comes down to how to handle CDATA, either with the approach you used http://stackoverflow.com/questions/3650203/getting-cdata-content-while-parsing-xml-file or casting with `(string)`, which unfortunately didn't work with me, either.

Side note / more fun in debugging, since that heroku-wp uses HipHop, I ran into this: http://stackoverflow.com/questions/28015051/phpinfo-not-working-correctly-in-hhvm :D the recommended HHVMInfo has DB credentials but I'm happy to share it privately, if that might be of help.

According to http://php.net/manual/en/function.simplexml-load-file.php#82067 your method should work as of 5.1, and I'm running 5.6.

Edit: Looks like this has been called out https://github.com/facebook/hhvm/issues/650

HHVM definitely seems edge case to me, but bummer that it's the one (/ recommended) way to get WordPress up and running quickly.

I'll keep digging.

**Comment by bahoo** [comment]
This is now irrelevant. Don't run this on Heroku / HHVM.

**Comment by atticoos** [comment]
Oh man, the best kind of issue closure
